<a href="https://colab.research.google.com/github/anshupandey/natural_language_processing/blob/master/Case_Study_Sentiment_Analysis_Amazon_Mobile_Reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Study: Sentiment Analysis

### Data Prep

In [0]:
# THis dataset also requires cleaning text and removing unwanted tokens using regular expressions,
# this part is not covered in this notebook to save time but strongly recommeded to perform.

In [0]:
import pandas as pd
import numpy as np

# Read in the data
df = pd.read_csv(r"https://media.githubusercontent.com/media/anshupandey/Machine_Learning_Training/master/datasets/Amazon_Unlocked_Mobile.csv")
print(df.shape)
# Sample the data to speed up computation
df = df.sample(frac=0.1, random_state=10)
print(df.shape)
df.head()

(413840, 6)
(41384, 6)


Product Name  ... Review Votes
394349  Sony XPERIA Z2 D6503 FACTORY UNLOCKED Internat...  ...          0.0
34377       Apple iPhone 5c 8GB (Pink) - Verizon Wireless  ...          1.0
248521  Motorola Droid RAZR MAXX XT912 M Verizon Smart...  ...          3.0
167661  CNPGD [U.S. Office Extended Warranty] Smartwat...  ...          0.0
73287   Apple iPhone 7 Unlocked Phone 256 GB - US Vers...  ...          1.0

[5 rows x 6 columns]

In [0]:
# Drop missing values
df.dropna(inplace=True)

# Remove any 'neutral' ratings equal to 3
df = df[df['Rating'] != 3]

# Encode 4s and 5s as 1 (rated positively)
# Encode 1s and 2s as 0 (rated poorly)
df['Positively Rated'] = np.where(df['Rating'] > 3, 1, 0)
df.head(10)

Product Name  ... Positively Rated
34377       Apple iPhone 5c 8GB (Pink) - Verizon Wireless  ...                0
248521  Motorola Droid RAZR MAXX XT912 M Verizon Smart...  ...                1
167661  CNPGD [U.S. Office Extended Warranty] Smartwat...  ...                0
73287   Apple iPhone 7 Unlocked Phone 256 GB - US Vers...  ...                1
277158  Nokia N8 Unlocked GSM Touch Screen Phone Featu...  ...                1
100311  Blackberry Torch 2 9810 Unlocked Phone with 1....  ...                1
251669  Motorola Moto E (1st Generation) - Black - 4 G...  ...                1
279878  OtterBox 77-29864 Defender Series Hybrid Case ...  ...                1
406017  Verizon HTC Rezound 4G Android Smarphone - 8MP...  ...                1
302567  RCA M1 Unlocked Cell Phone, Dual Sim, 5Mp Came...  ...                1

[10 rows x 7 columns]

In [0]:
# Most ratings are positive
df['Positively Rated'].mean()

0.7471776686078667

In [0]:
from sklearn.model_selection import train_test_split

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(df['Reviews'], 
                                                    df['Positively Rated'], 
                                                    random_state=0)

In [0]:
print('X_train first entry:\n\n', X_train.iloc[0])
print('\n\nX_train shape: ', X_train.shape)

X_train first entry:

 Everything about it is awesome!


X_train shape:  (23052,)


In [0]:
X_train

78589                       Everything about it is awesome!
2581      I bought this phone in July of 2015, and I lov...
303780    Small and very light, simple, when just a phon...
369144                                        Awesome phone
390639    The phone is just as described. Looks sleek an...
310282                                            Very Good
396004    Good telephone and very stylish and slim. Batt...
139101                   excellent seller. I recommend 100%
308627    My old LG android phone was failed to update O...
397086    I've had a Samsung Galaxy S2, S3, and S4. I un...
257145    This Phone was as described New and the servic...
173255    This is a fun little device. It is a solid cel...
33680                                    It works very well
11109     My daughter just love her gift. Not an apple f...
67757                                                  Good
215420                                           Excellent!
369389                                  

# CountVectorizer

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

# Fit the CountVectorizer to the training data
vect = CountVectorizer().fit(X_train)

In [0]:
vect.get_feature_names()[::2000]

['00',
 'arroja',
 'comapañias',
 'dvds',
 'golden',
 'lands',
 'oil',
 'razonable',
 'smallsliver',
 'tweak']

In [0]:
len(vect.get_feature_names())

19601

In [0]:
# transform the documents in the training data to a document-term matrix
X_train_vectorized = vect.transform(X_train)

X_train_vectorized

<23052x19601 sparse matrix of type '<class 'numpy.int64'>'
	with 613289 stored elements in Compressed Sparse Row format>

In [0]:
from sklearn.linear_model import LogisticRegression

# Train the model
model = LogisticRegression()
model.fit(X_train_vectorized, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
# Predict the transformed test documents
predictions = model.predict(vect.transform(X_test))

In [0]:
model.score(vect.transform(X_test),y_test)

0.93181522446324

In [0]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.89      0.83      0.86      1933
           1       0.94      0.97      0.95      5752

    accuracy                           0.93      7685
   macro avg       0.92      0.90      0.91      7685
weighted avg       0.93      0.93      0.93      7685

[[1601  332]
 [ 192 5560]]


In [0]:
# get the feature names as numpy array
feature_names = np.array(vect.get_feature_names())

# Sort the coefficients from the model
sorted_coef_index = model.coef_[0].argsort()

# Find the 10 smallest and 10 largest coefficients
# The 10 largest coefficients are being indexed using [:-11:-1] 
# so the list returned is in order of largest to smallest
print('Smallest Coefs:\n{}\n'.format(feature_names[sorted_coef_index[:10]]))
print('Largest Coefs: \n{}'.format(feature_names[sorted_coef_index[:-11:-1]]))

Smallest Coefs:
['worst' 'terrible' 'slow' 'junk' 'poor' 'sucks' 'horrible' 'useless'
 'waste' 'disappointed']

Largest Coefs: 
['excelent' 'excelente' 'excellent' 'perfectly' 'love' 'perfect' 'exactly'
 'great' 'best' 'awesome']


# Tfidf

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Fit the TfidfVectorizer to the training data specifiying a minimum document frequency of 5
vect = TfidfVectorizer(min_df=5).fit(X_train)
len(vect.get_feature_names())

5442

In [0]:
X_train_vectorized = vect.transform(X_train)

model = LogisticRegression()
model.fit(X_train_vectorized, y_train)

predictions = model.predict(vect.transform(X_test))

print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.90      0.81      0.85      1933
           1       0.94      0.97      0.95      5752

    accuracy                           0.93      7685
   macro avg       0.92      0.89      0.90      7685
weighted avg       0.93      0.93      0.93      7685

[[1563  370]
 [ 165 5587]]


In [0]:
feature_names = np.array(vect.get_feature_names())

sorted_tfidf_index = X_train_vectorized.max(0).toarray()[0].argsort()

print('Smallest tfidf:\n{}\n'.format(feature_names[sorted_tfidf_index[:10]]))
print('Largest tfidf: \n{}'.format(feature_names[sorted_tfidf_index[:-11:-1]]))

Smallest tfidf:
['61' 'printer' 'approach' 'adjustment' 'consequences' 'length' 'emailing'
 'degrees' 'handsfree' 'chipset']

Largest tfidf: 
['unlocked' 'handy' 'useless' 'cheat' 'up' 'original' 'exelent' 'exelente'
 'exellent' 'satisfied']


In [0]:
sorted_coef_index = model.coef_[0].argsort()

print('Smallest Coefs:\n{}\n'.format(feature_names[sorted_coef_index[:10]]))
print('Largest Coefs: \n{}'.format(feature_names[sorted_coef_index[:-11:-1]]))

Smallest Coefs:
['not' 'slow' 'disappointed' 'worst' 'terrible' 'never' 'return' 'doesn'
 'horrible' 'waste']

Largest Coefs: 
['great' 'love' 'excellent' 'good' 'best' 'perfect' 'price' 'awesome'
 'far' 'perfectly']


In [0]:
# These reviews are treated the same by our current model
print(model.predict(vect.transform(['not an issue, phone is working',
                                    'an issue, phone is not working'])))

[0 0]


# n-grams

In [0]:
# Fit the CountVectorizer to the training data specifiying a minimum 
# document frequency of 5 and extracting 1-grams and 2-grams
vect = CountVectorizer(min_df=5, ngram_range=(1,2)).fit(X_train)

X_train_vectorized = vect.transform(X_train)

len(vect.get_feature_names())

29072

In [0]:
model = LogisticRegression()
model.fit(X_train_vectorized, y_train)

predictions = model.predict(vect.transform(X_test))

print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.90      0.85      0.88      1933
           1       0.95      0.97      0.96      5752

    accuracy                           0.94      7685
   macro avg       0.93      0.91      0.92      7685
weighted avg       0.94      0.94      0.94      7685

[[1649  284]
 [ 178 5574]]


In [0]:
feature_names = np.array(vect.get_feature_names())

sorted_coef_index = model.coef_[0].argsort()

print('Smallest Coefs:\n{}\n'.format(feature_names[sorted_coef_index[:10]]))
print('Largest Coefs: \n{}'.format(feature_names[sorted_coef_index[:-11:-1]]))

Smallest Coefs:
['no good' 'junk' 'poor' 'slow' 'worst' 'broken' 'not good' 'terrible'
 'defective' 'horrible']

Largest Coefs: 
['excellent' 'excelente' 'excelent' 'perfect' 'great' 'love' 'awesome'
 'no problems' 'good' 'best']


In [0]:
# These reviews are now correctly identified
print(model.predict(vect.transform(['not an issue, phone is working',
                                    'an issue, phone is not working'])))

[1 0]


# LSTM

In [0]:
!pip install tensorflow
!pip install keras

In [0]:
from keras import models,layers
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [0]:
x= df['Reviews']
y = df['Positively Rated']
print(x.shape)
print(y.shape)

(30737,)
(30737,)


In [0]:
# The maximum number of words to be used. (most frequent)
MAX_NB_WORDS = 20000
# Max number of words in each complaint.
MAX_SEQUENCE_LENGTH = 250
# This is fixed.
EMBEDDING_DIM = 120

tokenizer = Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', 
                      lower=True)

tokenizer.fit_on_texts(x.values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 23534 unique tokens.


In [0]:
#making every reviview of size 250 tokens
x = tokenizer.texts_to_sequences(x.values)
x = pad_sequences(x, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', x.shape)

Shape of data tensor: (30737, 250)


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size = 0.10, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(27663, 250) (27663,)
(3074, 250) (3074,)


In [0]:
model = models.Sequential()
model.add(layers.Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=x.shape[1]))
model.add(layers.SpatialDropout1D(0.2))
model.add(layers.LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(X_train, Y_train, epochs=10, batch_size=100,validation_data=(X_test,Y_test),
                    verbose=True)





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 27663 samples, validate on 3074 samples
Epoch 1/10
27663/27663 [==============================] - 211s 8ms/step - loss: 0.3135 - acc: 0.8649 - val_loss: 0.1959 - val_acc: 0.9294
Epoch 2/10
27663/27663 [==============================] - 210s 8ms/step - loss: 0.1719 - acc: 0.9379 - val_loss: 0.1973 - val_acc: 0.9239
Epoch 3/10
27663/27663 [==============================] - 211s 8ms/step - loss: 0.1336 - acc: 0.9519 - val_loss: 0.1760 - val_acc: 0.9388
Epoch 4/10
27663/27663 [==============================] - 210s 8ms/step - loss: 0.1060 - acc: 0.9638 - val_loss: 0.1834 - val_acc: 0.9343
Epoch 5/10
27663/27663 [==============================] - 210s 8ms/step - loss: 0.0915 - acc: 0.9693 - val_loss: 0.1861 - val_acc: 0.9418
Epoch 6/10
27663/27663 [======================

In [0]:
loss,accr = model.evaluate(X_test,Y_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(loss,accr))

In [0]:
predictions = model.predict_classes(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

In [0]:
plt.title('Loss')
plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='test')
plt.legend()
plt.show()

In [0]:
plt.title('Accuracy')
plt.plot(history.history['acc'], label='train')
plt.plot(history.history['val_acc'], label='test')
plt.legend()
plt.show()