<a href="https://colab.research.google.com/github/anshupandey/Natural_language_Processing/blob/master/GPT2_using_huggingface_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

     |████████████████████████████████| 2.6 MB 5.3 MB/s 
     |████████████████████████████████| 3.3 MB 39.0 MB/s 
     |████████████████████████████████| 636 kB 42.0 MB/s 
     |████████████████████████████████| 895 kB 36.0 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2") #gpt2-medium, gpt-large
tokenizer("Hello world")['input_ids']

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

[15496, 995]

In [3]:
tokenizer("Hello world")['input_ids']

[15496, 995]

In [4]:
tokenizer(" Hello world")['input_ids']

[18435, 995]

In [5]:
tokenizer(" Hello world my name is anshu")['input_ids']

[18435, 995, 616, 1438, 318, 281, 1477, 84]

In [6]:
import tensorflow.python.ops.numpy_ops.np_config
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()

In [7]:
import numpy as np

In [8]:
from transformers import GPT2Model
model = GPT2Model.from_pretrained('gpt2')
# gpt2 = 12 layers - 768 dimensional vector
# gpt2-medium = 24 layers - 1024 dimensional vector
# gpt2-large = 36 layers - 1280 dimensional vector

inputs = tokenizer("hi, my dog is cute, how are you", return_tensors="pt")['input_ids']
outputs = model(inputs)

last_hidden_states = outputs.last_hidden_state

last_hidden_states.shape

Downloading:   0%|          | 0.00/548M [00:00<?, ?B/s]

torch.Size([1, 10, 768])

In [9]:
inputs

tensor([[ 5303,    11,   616,  3290,   318, 13779,    11,   703,   389,   345]])

In [10]:
last_hidden_states.cpu().detach().numpy().shape

(1, 10, 768)

In [11]:
# get sentence vectorization - take the vector of the last token = equivalent to sentence tokenization
last_hidden_states.cpu().detach().numpy()[0,-1,:].shape

(768,)

In [21]:
def doc2vec(doc):
  inputs = tokenizer(doc, return_tensors="pt")['input_ids']
  outputs = model(inputs)
  last_hidden_states = outputs.last_hidden_state
  vec = last_hidden_states.cpu().detach().numpy()[0,-1,:]
  vec = vec.reshape(-1,768)
  return vec

In [24]:
doc1 = "Hi, the world looks more wonderful today."
doc2 = "Hello, it looks like the world is more beautiful today."
vec1 = doc2vec(doc1)
vec2 = doc2vec(doc2)

In [25]:
vec1.shape

(1, 768)

In [26]:
from sklearn import metrics

In [27]:
metrics.pairwise.cosine_similarity(vec1,vec2)

array([[0.9998336]], dtype=float32)

In [32]:
doc1 = "Hi, the world looks more wonderful today, i love such amazing days and its beautiful."
doc2 = "john bought a watch and it was costly, bad and he disliked that watch which was black in color and dirty"
vec1 = doc2vec(doc1)
vec2 = doc2vec(doc2)
metrics.pairwise.cosine_similarity(vec1,vec2)

array([[0.9888277]], dtype=float32)