<a href="https://colab.research.google.com/github/anshupandey/Natural_language_Processing/blob/master/NLP%20-%20Transfer%20Learning/GPT2_using_huggingface_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

In [ ]:
from transformers import GPT2Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2") #gpt2-medium, gpt-large
tokenizer("Hello world")['input_ids']

In [ ]:
tokenizer("Hello world")['input_ids']

In [ ]:
tokenizer(" Hello world")['input_ids']

In [ ]:
tokenizer(" Hello world my name is anshu")['input_ids']

In [ ]:
import tensorflow.python.ops.numpy_ops.np_config
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()

In [ ]:
import numpy as np

In [ ]:
from transformers import GPT2Model
model = GPT2Model.from_pretrained('gpt2')
# gpt2 = 12 layers - 768 dimensional vector
# gpt2-medium = 24 layers - 1024 dimensional vector
# gpt2-large = 36 layers - 1280 dimensional vector

inputs = tokenizer("hi, my dog is cute, how are you", return_tensors="pt")['input_ids']
print(inputs)
outputs = model(inputs)

last_hidden_states = outputs.last_hidden_state

last_hidden_states.shape

tensor([[ 5303,    11,   616,  3290,   318, 13779,    11,   703,   389,   345]])


torch.Size([1, 10, 768])

In [ ]:
inputs

tensor([[ 5303,    11,   616,  3290,   318, 13779,    11,   703,   389,   345]])

In [ ]:
last_hidden_states.cpu().detach().numpy().shape

(1, 10, 768)

In [ ]:
# get sentence vectorization - take the vector of the last token = equivalent to sentence tokenization
last_hidden_states.cpu().detach().numpy()[0,-1,:].shape

(768,)

In [ ]:
def doc2vec(doc):
  inputs = tokenizer(doc, return_tensors="pt")['input_ids']
  outputs = model(inputs)
  last_hidden_states = outputs.last_hidden_state
  vec = last_hidden_states.cpu().detach().numpy()[0,-1,:]
  vec = vec.reshape(-1,768)
  return vec

In [ ]:
doc1 = "Hi, the world looks more wonderful today."
doc2 = "Hello, it looks like the world is more beautiful today."
vec1 = doc2vec(doc1)
vec2 = doc2vec(doc2)

In [ ]:
vec1.shape

(1, 768)

In [ ]:
from sklearn import metrics

In [ ]:
metrics.pairwise.cosine_similarity(vec1,vec2)

array([[0.9998337]], dtype=float32)

In [ ]:
doc1 = "Hi, the world looks more wonderful today, i love such amazing days and its beautiful."
doc2 = "john bought a watch and it was costly, bad and he disliked that watch which was black in color and dirty"
vec1 = doc2vec(doc1)
vec2 = doc2vec(doc2)
metrics.pairwise.cosine_similarity(vec1,vec2)

array([[0.98882776]], dtype=float32)

## Text Generation with GPT

In [ ]:
from transformers import pipeline
gpt_generator = pipeline('text-generation',model='gpt2')

In [ ]:
doc = "Python is beautiful"

In [ ]:
sentences = gpt_generator(doc,do_sample=True,top_k=50,max_length=128,num_return_sequences=5)

for sent in sentences:
  print(sent['generated_text'])
  print("************************************************")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Python is beautiful to use, especially in an interview environment but not all of a sudden you have to create a complex API. Even this way you are always left with using the API itself.

The main issue that we can overcome is to keep the data short and clean to prevent accidental corruption of the data structure and to make clean API calls with an interface that is very easy to understand and understood by beginners. Because of that, I think I can recommend the tutorial by Robert Littman called "The Power of Python" (pdf, 539kB).

The basic way to get acquainted with Python is by working as an
************************************************
Python is beautiful. It's also perfect for working with an API that you just have to know how to implement.

CocoaPods is another gem that I haven't used for quite a while, but that was so awesome so when I wrote it I did it. Because you can still build your own.

So, I've got this tutorial for you. It's a quick demonstration of what it does best.


In [ ]:
doc = """
imort matplotlib.pyplot as plt

image = 'image.jpg'

# load the image
"""

print(gpt_generator(doc,do_sample=True,top_k=10,max_length=256,temperature=1)[0]['generated_text'])


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.



imort matplotlib.pyplot as plt

image = 'image.jpg'

# load the image

if image =='svg' :

image = 'img/v1.jpg'
.append(image, 'png/v1.png')

# create a new image

from plt.image import Image

from plt.utils import get_raw_data

from plt.utils import get_image_data as img

from plt.utils.pyplot import x,y

if img == None :

x = x[ 0 ].replace('/ ','\t')

y = y[ 0 ].replace('/ ','\t')

# load the img

if image =='svg' :

image = 'img/v1.gif'

.append(image, 'png/v1.png')

# load the img

#

# load the data from

from plt.image import Image

from plt.utils import get_raw_data as img

from plt.util
